In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

df = pd.read_csv("../../data/processed/processed_reviews.csv")
df.head()

,review,sentiment,clean_text
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stunnin...

In [2]:
X = df['clean_text']
y = df['sentiment']

In [11]:
bow_vectoraizer = CountVectorizer()
x_bow = bow_vectoraizer.fit_transform(X)
x_bow.shape

vocabulary = bow_vectoraizer.get_feature_names_out()

print("Number of features :",len(vocabulary))

Number of features : 89497

In [5]:
n_gram_vectorizer = CountVectorizer(
    ngram_range=(1,2)
)

x_ngram = n_gram_vectorizer.fit_transform(X)

n_gram_vocabulary = n_gram_vectorizer.get_feature_names_out()

n_gram_vocabulary[:50]

array(['aa', 'aa acting', 'aa date', 'aa doctor', 'aa group', 'aa jaega',
       'aa level', 'aa many', 'aa meeting', 'aa meri', 'aa not',
       'aa presentation', 'aa rating', 'aa uo', 'aaa', 'aaa ball',
       'aaa even', 'aaa famous', 'aaa favorite', 'aaa instance',
       'aaa jawani', 'aaa level', 'aaa nirupa', 'aaa no', 'aaa parvarish',
       'aaa time', 'aaa torn', 'aaa yeah', 'aaaaaaaaaaaahhhhhhhhhhhhhh',
       'aaaaaaaaaaaahhhhhhhhhhhhhh hurting', 'aaaaaaaargh', 'aaaaaaah',
       'aaaaaaah saw', 'aaaaaaahhhhhhggg', 'aaaaagh', 'aaaaagh scene',
       'aaaaah', 'aaaaah movie', 'aaaaah oh', 'aaaaahhhh',
       'aaaaahhhh get', 'aaaaargh', 'aaaaargh count',
       'aaaaarrrrrrgggggghhhhhh', 'aaaaarrrrrrgggggghhhhhh one', 'aaaaaw',
       'aaaaaw cry', 'aaaahhhhhh', 'aaaahhhhhh terrible', 'aaaahhhhhhh'],
      dtype=object)

In [6]:
bigram_vectorizer = CountVectorizer(
    ngram_range=(2,2)
)

x_bigram = bigram_vectorizer.fit_transform(X)
bi_gram_vocabulary = bigram_vectorizer.get_feature_names_out()

bi_gram_vocabulary[:50]

array(['aa acting', 'aa date', 'aa doctor', 'aa group', 'aa jaega',
       'aa level', 'aa many', 'aa meeting', 'aa meri', 'aa not',
       'aa presentation', 'aa rating', 'aa uo', 'aaa ball', 'aaa even',
       'aaa famous', 'aaa favorite', 'aaa instance', 'aaa jawani',
       'aaa level', 'aaa nirupa', 'aaa no', 'aaa parvarish', 'aaa time',
       'aaa torn', 'aaa yeah', 'aaaaaaaaaaaahhhhhhhhhhhhhh hurting',
       'aaaaaaah saw', 'aaaaagh scene', 'aaaaah movie', 'aaaaah oh',
       'aaaaahhhh get', 'aaaaargh count', 'aaaaarrrrrrgggggghhhhhh one',
       'aaaaaw cry', 'aaaahhhhhh terrible', 'aaaahhhhhhh run',
       'aaaand point', 'aaaarrgh former', 'aaaawwwwww well',
       'aaaggghhhhhhh ca', 'aaaghi actually', 'aaah friggin', 'aaah leg',
       'aaah see', 'aaahhhhhhh scene', 'aaall way', 'aaargh bad',
       'aaargh dead', 'aaargh fact'], dtype=object)

In [7]:
tfidf_vectorizer = TfidfVectorizer(stop_words=None)

X_tfidf = tfidf_vectorizer.fit_transform(X)

tfidf_vocablary = (tfidf_vectorizer.get_feature_names_out())
print(tfidf_vocablary[:50])

['aa' 'aaa' 'aaaaaaaaaaaahhhhhhhhhhhhhh' 'aaaaaaaargh' 'aaaaaaah'
 'aaaaaaahhhhhhggg' 'aaaaagh' 'aaaaah' 'aaaaahhhh' 'aaaaargh'
 'aaaaarrrrrrgggggghhhhhh' 'aaaaaw' 'aaaahhhhhh' 'aaaahhhhhhh' 'aaaand'
 'aaaarrgh' 'aaaawwwwww' 'aaaggghhhhhhh' 'aaaghi' 'aaah' 'aaahhhhhhh'
 'aaall' 'aaargh' 'aaarrrgh' 'aaaugh' 'aab' 'aachen' 'aada' 'aadha' 'aag'
 'aage' 'aagh' 'aaghh' 'aah' 'aahe' 'aahed' 'aahhh' 'aahhhh' 'aahing'
 'aaila' 'aailiyah' 'aaip' 'aaja' 'aajala' 'aak' 'aakash' 'aake' 'aaker'
 'aakrosh' 'aalcc']

In [8]:
tfidf_ngram_vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    stop_words=None

)

x_tfidf_ngram  = tfidf_ngram_vectorizer.fit_transform(X)

In [9]:
tfidf_limited = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words=None
)

X_tfidf_limited = tfidf_limited.fit_transform(X)

In [10]:
tfidf_min_df = TfidfVectorizer(
    min_df=2,
    ngram_range=(1, 2),
    stop_words=None
)

X_tfidf_min_df = tfidf_min_df.fit_transform(X)

In [12]:
representation_sizes = pd.DataFrame({
    "Representation": [
        "BoW",
        "Unigram + Bigram",
        "Bigram",
        "TF-IDF",
        "TF-IDF + Unigram + Bigram",
        "TF-IDF Limited",
        "TF-IDF min_df=2"
    ],
    "Documents": [
        x_bow.shape[0],
        x_ngram.shape[0],
        x_bigram.shape[0],
        X_tfidf.shape[0],
        x_tfidf_ngram.shape[0],
        X_tfidf_limited.shape[0],
        X_tfidf_min_df.shape[0]
    ],
    "Features": [
        x_bow.shape[1],
        x_ngram.shape[1],
        x_bigram.shape[1],
        X_tfidf.shape[1],
        x_tfidf_ngram.shape[1],
        X_tfidf_limited.shape[1],
        X_tfidf_min_df.shape[1]
    ]
})

representation_sizes

              Representation  Documents  Features
0                        BoW      50000     89497
1           Unigram + Bigram      50000   2875751
2                     Bigram      50000   2786254
3                     TF-IDF      50000     89497
4  TF-IDF + Unigram + Bigram      50000   2875751
5             TF-IDF Limited      50000     20000
6            TF-IDF min_df=2      50000    641536

In [14]:
comparison = pd.DataFrame({
    "Representation": [
        "BoW Unigram",
        "BoW Unigram + Bigram",
        "TF-IDF Unigram",
        "TF-IDF Unigram + Bigram"
    ],
    "Number of Features": [
        x_bow.shape[1],
        x_ngram.shape[1],
        X_tfidf.shape[1],
        x_tfidf_ngram.shape[1]
    ],
    "Average Non-Zero Features": [
        x_bow.getnnz(axis=1).mean(),
        x_ngram.getnnz(axis=1).mean(),
        X_tfidf.getnnz(axis=1).mean(),
        x_tfidf_ngram.getnnz(axis=1).mean()
    ]
})

comparison

            Representation  Number of Features  Average Non-Zero Features
0              BoW Unigram               89497                   91.98036
1     BoW Unigram + Bigram             2875751                  203.42228
2           TF-IDF Unigram               89497                   91.98036
3  TF-IDF Unigram + Bigram             2875751                  203.42228

In [15]:
def calculate_sparsity(matrix):
    total_elements = matrix.shape[0] * matrix.shape[1]
    non_zero_elements = matrix.nnz

    return (
        1 - non_zero_elements / total_elements
    ) * 100

In [17]:
results = pd.DataFrame({
    "Representation": [
        "BoW Unigram",
        "BoW Unigram + Bigram",
        "TF-IDF Unigram",
        "TF-IDF Unigram + Bigram"
    ],
    "Features": [
        x_bow.shape[1],
        x_ngram.shape[1],
        X_tfidf.shape[1],
        x_tfidf_ngram.shape[1]
    ],
    "Average Non-Zero Features": [
        x_bow.getnnz(axis=1).mean(),
        x_ngram.getnnz(axis=1).mean(),
        X_tfidf.getnnz(axis=1).mean(),
        x_tfidf_ngram.getnnz(axis=1).mean()
    ],
    "Sparsity (%)": [
        calculate_sparsity(x_bow),
        calculate_sparsity(x_ngram),
        calculate_sparsity(X_tfidf),
        calculate_sparsity(x_tfidf_ngram)
    ]
})

results

            Representation  Features  Average Non-Zero Features  Sparsity (%)
0              BoW Unigram     89497                   91.98036     99.897225
1     BoW Unigram + Bigram   2875751                  203.42228     99.992926
2           TF-IDF Unigram     89497                   91.98036     99.897225
3  TF-IDF Unigram + Bigram   2875751                  203.42228     99.992926

In [19]:
sample_index = 0

bow_values = x_bow[sample_index].toarray().ravel()
tfidf_values = X_tfidf[sample_index].toarray().ravel()

value_comparison = pd.DataFrame({
    "term": tfidf_vocablary,
    "bow_value": bow_values,
    "tfidf_value": tfidf_values
})

value_comparison = value_comparison[
    value_comparison["bow_value"] > 0
]

value_comparison.sort_values(
    "tfidf_value",
    ascending=False
).head(20)

              term  bow_value  tfidf_value
57186           oz          6     0.475534
85232     violence          4     0.209631
61637       prison          3     0.191283
39262       inmate          2     0.171095
29347       forget          3     0.164966
75684       struck          2     0.148435
71172         show          4     0.128068
40085      inwards          1     0.127127
58544  penitentary          1     0.127127
54222       nickel          1     0.110689
24617      emerald          1     0.108861
69403      scuffle          1     0.108043
23140          due          2     0.104743
14146         city          2     0.102537
61651      privacy          1     0.101986
56536       oswald          1     0.101986
4171         aryan          1     0.100226
82888  unflinching          1     0.099058
30810      gangsta          1     0.097996
79679        timid          1     0.094500

In [23]:
review_index = 0

bow_review = x_bow[review_index]
tfidf_review = X_tfidf[review_index]

terms = bow_vectoraizer.get_feature_names_out()

review_comparison = pd.DataFrame({
    "term": terms,
    "bow_count": bow_review.toarray().ravel(),
    "tfidf_weight": tfidf_review.toarray().ravel()
})

review_comparison = review_comparison[
    review_comparison["bow_count"] > 0
]

review_comparison.sort_values(
    "tfidf_weight",
    ascending=False
).head(20)

              term  bow_count  tfidf_weight
57186           oz          6      0.475534
85232     violence          4      0.209631
61637       prison          3      0.191283
39262       inmate          2      0.171095
29347       forget          3      0.164966
75684       struck          2      0.148435
71172         show          4      0.128068
40085      inwards          1      0.127127
58544  penitentary          1      0.127127
54222       nickel          1      0.110689
24617      emerald          1      0.108861
69403      scuffle          1      0.108043
23140          due          2      0.104743
14146         city          2      0.102537
61651      privacy          1      0.101986
56536       oswald          1      0.101986
4171         aryan          1      0.100226
82888  unflinching          1      0.099058
30810      gangsta          1      0.097996
79679        timid          1      0.094500

In [24]:
mean_tfidf = np.asarray(
    X_tfidf.mean(axis=0)
).ravel()

tfidf_terms = pd.DataFrame({
    "term": tfidf_vocablary,
    "mean_tfidf": mean_tfidf
})

tfidf_terms.sort_values(
    "mean_tfidf",
    ascending=False
).head(20)

            term  mean_tfidf
52435      movie    0.053047
28145       film    0.043754
54868        not    0.029737
55978        one    0.026310
45701       like    0.022611
32497       good    0.019809
79626       time    0.018636
12929  character    0.017886
88000      would    0.017515
75340      story    0.017277
64032     really    0.017123
69658        see    0.016590
54528         no    0.016254
26002       even    0.016144
31515        get    0.015888
5446         bad    0.015786
47781       make    0.015657
33069      great    0.014959
68797      scene    0.014554
71172       show    0.014403

In [25]:
tfidf_ngram_vocabulary = (
    tfidf_ngram_vectorizer
    .get_feature_names_out()
)

print(
    "Total features:",
    len(tfidf_ngram_vocabulary)
)

Total features: 2875751

In [26]:
unigram_features = X_tfidf.shape[1]
bigram_features = x_tfidf_ngram.shape[1]

increase = (
    (bigram_features - unigram_features)
    / unigram_features
) * 100

print(
    f"Feature increase: {increase:.2f}%"
)

Feature increase: 3113.24%

In [27]:
final_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    max_features=20000
)

X_final = final_vectorizer.fit_transform(X)

In [28]:
import os
import joblib

os.makedirs(
    "../artifacts",
    exist_ok=True
)

joblib.dump(
    final_vectorizer,
    "../artifacts/tfidf_vectorizer.pkl"
)

['../artifacts/tfidf_vectorizer.pkl']